differnet hass chart

diff --git a/kubernetes/apps/default/home-assistant/app/helmrelease.yaml b/kubernetes/apps/default/home-assistant/app/helmrelease.yaml
--- a/kubernetes/apps/default/home-assistant/app/helmrelease.yaml
+++ b/kubernetes/apps/default/home-assistant/app/helmrelease.yaml
@@ -19,27 +19,44 @@ spec:
   values:
     controllers:
       home-assistant:
-        annotations:
-          reloader.stakater.com/auto: "true"
         containers:
-          app:
+          home-assistant:
             image:
               repository: ghcr.io/home-operations/home-assistant
-              tag: 2025.6.3
-            env:
-              VENV_FOLDER: /venv
-            # envFrom:
-            #   - secretRef:
-            #       name: home-assistant-secret
-            securityContext:
-              allowPrivilegeEscalation: false
-              readOnlyRootFilesystem: true
-              capabilities: { drop: ["ALL"] }
-            resources:
-              requests:
-                cpu: 10m
-              limits:
-                memory: 2Gi
+              tag: 2025.6.1
+          code:
+            dependsOn: home-assistant
+            image:
+              repository: ghcr.io/coder/code-server
+              tag: 4.101.1
+            args:
+              - --auth
+              - "none"
+              - --user-data-dir
+              - "/config/.vscode"
+              - --extensions-dir
+              - "/config/.vscode"
+              - --port
+              - "8081"
+              - "/config"
+        initContainers:
+          ensure-config:
+            image:
+              repository: busybox
+              tag: latest
+            command:
+              - /bin/sh
+              - -c
+              - |
+                CONFIG_FILE="/config/configuration.yaml"
+                if ! grep -q "trusted_proxies" "$CONFIG_FILE"; then
+                  echo "Adding missing http settings..."
+                  echo "" >> "$CONFIG_FILE"
+                  echo "http:" >> "$CONFIG_FILE"
+                  echo "  use_x_forwarded_for: true" >> "$CONFIG_FILE"
+                  echo "  trusted_proxies:" >> "$CONFIG_FILE"
+                  echo "    - 10.42.0.0/16" >> "$CONFIG_FILE"
+                fi
     defaultPodOptions:
       securityContext:
         runAsNonRoot: true
